<?php
/* DRUPAL HOOKS */

/**
 * Implements hook_theme().
 */
function phparch_theme($existing, $type, $theme, $path) {
    return array(
        'phparch_current_weather' => array(
            'variables' => array(
                'location' => NULL,
                'zipcode' => NULL,
                'temperature' => NULL,
                'description' => NULL,
            ),
            'template' => 'phpa-current-weather',
        ),
    );
}
